//
//  ADataService.m
//  aVoice
//
//  Created by aronliang on 2017/6/22.
//  Copyright © 2017年 aliexpress. All rights reserved.
//

#import "ADataService.h"
#import "AWordListViewModel.h"

@implementation ADataService

-(NSMutableArray*) getChapterList:(NSString*)userType{
    NSMutableArray* originArray = nil;
    if([userType isEqualToString:@"children"]){
        originArray =[NSMutableArray arrayWithObjects:
                      @"Unite1",@"Unite2",@"Unite3",@"Unite4",@"Unite5",@"Unite6",
                      nil];
    }
    else if([userType isEqualToString:@"adult"]){
        originArray =[NSMutableArray arrayWithObjects:
                      @"Unite1",@"Unite2",@"Unite3",@"Unite4",@"Unite5",@"Unite6",@"Unite7",@"Unite8",@"Unite9",@"Unite10",
                      @"Unite11",@"Unite12",@"Unite13",@"Unite14",@"Unite15",
                      nil];
    }
    else if([userType isEqualToString:@"root"]){
        originArray =[NSMutableArray arrayWithObjects:
                      @"Unite1",
                      nil];
    }
    
    return originArray;
}

-(NSMutableArray*) getWordList:(NSString*)userType chapter:(NSString*)chapter{
    
    NSMutableArray* originArray = nil;
    if([userType isEqualToString:@"children"]){
        if([chapter isEqualToString:@"Unite1"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"angry",@"生气的",
                          @"friendly",@"友好的",
                          @"funny",@"滑稽的",
                          @"happy",@"快乐的",
                          @"mean",@"吝啬的,破旧的",
                          @"noisy",@"吵吵闹闹的",
                          @"naughty",@"顽皮的,淘气的",
                          @"quiet",@"清静的",
                          @"sad",@"糟糕的,悲哀的",
                          @"scary",@"胆小的",
                          @"shy",@"害羞的",
                          @"unfriendly",@"不友好的",
                          @"hairy",@"多毛的",
                          @"pretty",@"漂亮的",
                          @"ugly",@"丑陋的",
                          nil];

        }
        else if ([chapter isEqualToString:@"Unite2"]){
            originArray =[NSMutableArray arrayWithObjects:
            @"Monday",@"星期一",
            @"Tuesday",@"星期二",
            @"Wednesday",@"星期三",
            @"Thursday",@"星期四",
            @"Firday",@"星期五",
            @"Saturday",@"星期六",
            @"Sunday",@"星期天",
            @"morning",@"早上",
            @"afternoon",@"下午",
            @"evening",@"傍晚",
            @"night",@"晚上",
            @"boat",@"小船",
            @"bus",@"巴士",
            @"plane",@"飞机",
            @"taxi",@"出租车",
            @"train",@"火车",
            @"picnic",@"野餐郊游",
            @"beach",@"海滩",
            @"countryside",@"乡村",
            @"desert",@"沙漠",
            @"island",@"岛",
            @"lake",@"湖",
            @"mountain",@"山脉",
            @"park",@"公园",
            @"zoo",@"动物园",
            nil];
        }
        else if ([chapter isEqualToString:@"Unite3"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"get up",@"站起来、起床",
                          @"take a shower",@"沐浴",
                          @"have breakfast",@"吃早饭",
                          @"go shopping",@"去买东西",
                          @"art",@"艺术",
                          @"computer class",@"计算机课",
                          @"English",@"英语",
                          @"have lunch",@"吃午餐",
                          @"play sports",@"参加体育运动或比赛",
                          @"play with friends",@"朋友玩",
                          @"have dinner",@"吃晚饭",
                          @"geography",@"地理",
                          @"history",@"历史学",
                          @"math",@"数学",
                          @"do homework",@"做作业",
                          @"play computer games",@"玩电脑游戏",
                          @"go to bed",@"去睡觉",
                          @"music",@"音乐",
                          @"P.E.",@"体育课",
                          @"science",@"科学",
                          nil];
            
        }
        else if ([chapter isEqualToString:@"Unite4"]){
            originArray =[NSMutableArray arrayWithObjects:
            @"cloudy",@"多云的; 阴天的",
            @"rain",@"雨",
            @"snow",@"雪花",
            @"stormy",@"暴风雨般的",
            @"sunny",@"照到阳光的",
            @"boots",@"长统靴",
            @"coat",@"上衣，外套",
            @"earmuffs",@"护耳",
            @"gloves",@"手套",
            @"jacket",@"短上衣，夹克",
            @"rain boots",@"防水靴",
            @"raincoat",@"雨衣",
            @"cold",@"寒冷的",
            @"cool",@"凉爽的",
            @"heavy",@"沉重的",
            @"hot",@"热的",
            @"light",@"光",
            @"sandals",@"拖鞋",
            @"scarf",@"围巾",
            @"sunnblock",@"防晒霜",
            @"sunglasses",@"太阳镜",
            @"swimsuit",@"游泳衣",
            @"towel",@"毛巾",
            @"umbrella",@"雨伞",
            @"strong",@"强烈的",
            @"warm",@"热情的",
            @"wet",@"湿的; 下雨的",
            @"windy",@"有风的",
            @"heart-shaped",@"心形的",
            @"round",@"圆形的",
            @"soft",@"柔软的",
            @"square",@"正方形",
            @"thick",@"茂密的",
            @"thin",@"瘦的",
                          nil];
        }
        else if ([chapter isEqualToString:@"Unite5"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"January",@"一月",
                          @"February",@"二月",
                          @"March",@"三月",
                          @"April",@"四月",
                          @"May",@"五月",
                          @"June",@"六月",
                          @"July",@"七月",
                          @"August",@"八月",
                          @"September",@"九月",
                          @"October",@"十月",
                          @"November",@"十一月",
                          @"December",@"十二月",
                          @"blow out candles",@"吹灭蜡烛",
                          @"blow up balloons",@"吹气球",
                          @"do face-painting",@"做鬼脸",
                          @"hang streamers",@"挂上彩带",
                          @"make a cake",@"制做蛋糕",
                          @"play games",@"做游戏",
                          @"play on a bouncy castle",@"在充气城堡里玩",
                          @"clown",@"小丑",
                          @"juggler",@"杂耍",
                          @"magician",@"魔术师",
                          @"wrap presents",@"包装礼物",
                          @"wrap gifts",@"包装礼物",
                          nil];
            
        }
        else if ([chapter isEqualToString:@"Unite6"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"apple pie",@"苹果馅饼",
                          @"curry",@"咖喱食品",
                          @"fried rice",@"炒饭",
                          @"milk",@"奶",
                          @"pancake",@"薄煎饼",
                          @"soup",@"汤",
                          @"spaghetti",@"意大利面条",
                          @"steak",@"牛排",
                          @"bowl",@"碗",
                          @"chopaticks",@"筷子",
                          @"fork",@"餐叉",
                          @"knife",@"刀",
                          @"menu",@"菜单",
                          @"napkin",@"餐巾",
                          @"plate",@"盘子，盆子",
                          @"spoon",@"匙，调羹",
                          @"waiter",@"服务员",
                          @"waitress",@"女服务员",
                          @"bad	",@"坏的",
                          @"delicious",@"美味的",
                          @"fresh",@"新鲜的",
                          @"good",@"好的; 优秀的",
                          @"juicy",@"多汁的",
                          @"old",@"老的",
                          @"nice",@"美好的",
                          @"salty",@"咸的",
                          @"sour",@"有酸味的",
                          @"spicy",@"辛辣的",
                          @"sweet",@"甜的",
                          nil];
        }
    }
    else if([userType isEqualToString:@"adult"]){
        if([chapter isEqualToString:@"Unite15"]){
        originArray =[NSMutableArray arrayWithObjects:
                      @"exclusive",@"独家",
                      @"detach",@"分离",
                      @"biography",@"档案",
                      @"translucent",@"透明",
                      @"opaque",@"不透明",
                      @"nonce",@"目前",
                      @"alias",@"别名",
                      @"collage",@"拼贴",
                      @"entity",@"实体",
                      @"iterator",@"迭代",
                      @"recommend",@"推荐",
                      @"deprecated",@"弃用",
                      @"welfare",@"福利",
                      @"abuse",@"滥用",
                      @"Adorable",@"可爱的",
                      @"ceiling",@"天花板",
                      @"retrieved",@"恢复",
                      @"supplementary",@"补充者",
                      @"archive",@"档案文件",
                      @"plain",@"平原",
                      @"aspect",@"方面",
                      @"diverged",@"分歧",
                      @"disposable",@"可任意处理的",
                      @"inactive",@"不活跃的",
                      @"asset",@"资产",
                      @"Aggressive",@"侵略性的",
                      @"desire",@"欲望",
                      @"restrain",@"抑制",
                      @"courage",@"勇气",
                      @"persistent",@"固执",
                      @"specific",@"特定",
                      @"sweep",@"打扫",
                      @"trailing",@"拖尾",
                     @"leading",@"领导",
                      @"mate",@"助手",
                      @"integration",@"集成",
                      @"Consignee",@"收件人",
                      @"compensate",@"补偿",
                      @"thick",@"厚的",
                      @"profit",@"利润",
                      @"Nutrition",@"营养",
                      @"virgin",@"处女",
                      @"tangles",@"缠结",
                      @"stiff",@"呆板",
                      @"refund",@"退款",
                      @"partial",@"局部",
                      @"density",@"密度",
                      @"closure",@"关闭",
                      @"objection",@"反对",
                      @"dispute",@"辩论",
                      @"massive",@"大量的",
                      @"recite",@"背诵",
                      @"objectionable",@"讨厌的",
                      @"excessively",@"过分",
                      @"spark",@"火花",
                      @"mortality",@"死亡数",
                      @"immorality",@"不道德",
                      @"Escapes",@"逸",
                      @"Percent",@"百分比",
                      @"disgusting",@"令人厌恶的",
                      @"garret",@"阁楼",
                      @"prolific",@"多产的",
                      @"oddly",@"古怪地",
                      @"overhead",@"天花板",
                      @"incubator",@"孵卵器",
                      @"Tuple",@"元组",
                      @"manifest",@"货单",
                      @"discretion",@"判定",
                      nil];
        }
        else if([chapter isEqualToString:@"Unite14"]){
            originArray =[NSMutableArray arrayWithObjects:
            @"Faggot",@"捆",
            @"scalable",@"可称量的",
            @"destiny",@" 命运",
            @"opponent",@"对手",
            @"cognitive",@"认知的",
            @"frontier",@"前沿",
            @"pessimistic",@"悲观的",
            @"agile",@"敏捷的",
            @"perspective",@"观点",
            @"inspired",@"激发",
            @"misuse",@"滥用",
            @"parallelism",@" 平行",
            @"semantic",@"语义的",
            @"disambiguation",@"消除模棱两可情况",
            @"bandwagon",@"流行",
            @"innocent",@"天真的人",
            @"outrageous",@"粗暴的",
            @"exposed",@"暴露",
            @"agnostic",@"不可知论者",
            @"Infrastructure",@"基础设施",
            @"recovery",@"恢复",
            @"obscure",@"昏暗的",
            @"ammo",@"弹药",
            @"ethnically",@"人种上",
            @"censor",@"审查",
            @"Leftists",@"左派",
            @"wrist",@"手腕",
            @"revealed",@"透露",
            @"sustained",@"维持",
            @"jammed",@"堵塞的",
            @"footage",@"英尺长度",
            @"negotiate",@"谈判",
            @"pragma",@"编译指示",
            @"inspire",@"激发",
            @"sparrow",@"麻雀",
            @"Intimate",@"知己",
            @"portrait",@"肖像",
            @"gazed",@" 凝视",
            @"embrace",@"拥抱",
            @"organic",@"有机的",
            @"present",@"现在",
            @"critical path",@" 关键路径",
            @"critical",@"危险的；决定性的；",
            @"discloser",@"揭露者",
            @"improper",@"不正确的",
            @"Bronze",@"青铜",
            @"Dimension",@"维",
            @"controversial",@"有争议的",
            @"declined",@"下降的",
            @"renowned",@"著名的",
            @"accomplish",@"完成",
            @"nexus",@"关系",
            @"assume",@"假定",
            @"jurisdiction",@" 司法权",
            @"variation",@"变化",
            @"venture",@"企业",
            @"equivalent",@"等价物",
            @"Brick",@"砖",
            @"outlets",@"出路",
            @"portal",@"大门",
            @"evident",@"明显的",
            @"infrastructure",@"基础设施",
            @"intrinsically",@"本质地",
            @"influence",@"影响",
            @"graph",@"图表",
            @"Flame",@"火焰",
            @"Recall",@"召回",
            @"Astral",@"星际的",
            @"distributed",@"分布式的",
            @"offender",@"冒犯",
            @"ballot",@"选举",
            @"priest",@"牧师",
            @"ramped up",@"增加",
            @"trends",@"趋势",
            @"engaged",@"保证",
            @"censorship",@"审查制度",
            @"dread",@"恐惧",
            nil];
        }
        else if([chapter isEqualToString:@"Unite13"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"nevertheless",@"然而",
                          @"influx",@"流入",
                          @"quantum",@"量子",
                          @"weirdo",@"古怪的人",
                          @"Ambassador",@"大使",
                          @"partition",@"划分",
                          @"quartz",@"石英",
                          @"audit",@"审计",
                          @"nested",@"嵌套的",
                          @"hobbies",@"兴趣爱好",
                          @"wholesale",@"批发",
                          @"uptown",@"住宅区",
                          @"funk",@"恐惧",
                          @"affairs",@"事务",
                          @"freakish",@"畸形的",
                          @"Locator",@"定位器",
                          @"emit",@"发出",
                          @"Shuffle",@"洗牌",
                          @"Metrics",@"度量",
                          @"Supervisor",@"监督人",
                          @"Deferred",@"延期的",
                          @"flaw",@"缺点",
                          @"domestic",@"国内的",
                          @"boon",@"恩惠",
                          @"criticisms",@"批评",
                          @"tumbled",@"翻滚",
                          @"gyrated",@"旋转",
                          @"startling",@"令人吃惊的",
                          @"plunged",@"投入",
                          @"testimony",@"证词",
                          @"turbulence",@"骚乱",
                          @"reminder",@"暗示",
                          @"pledge",@"保证",
                          @"Tearing up",@"撕毁",
                          @"paternity",@"父系",
                          @"derive",@"源于",
                          @"apparently",@"显然地",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite12"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"regrettable",@"令人遗憾的",
                          @"conviction",@"信念",
                          @"abhorrent",@"可恶的",
                          @"desire",@"欲望",
                          @"desirable",@"可取的",
                          @"aspirer",@"追求者",
                          @"character",@"性格",
                          @"corrupt",@"腐败的",
                          @"intentions",@"意图",
                          @"pervert",@"败坏",
                          @"perversions",@"扭曲",
                          @"vigorously",@"大力",
                          @"distinguish",@"区分",
                          @"surrender",@"投降",
                          @"propositon",@"命题",
                          @"duty",@"责任",
                          @"led to",@"导致",
                          @"pursued",@"追求",
                          @"conscience",@"良心",
                          @"honourable",@"尊敬的",
                          @"preserve",@"保存",
                          @"presence",@"出席",
                          @"alien",@"外星人",
                          @"alliance",@"联盟",
                          @"irrationality",@"非理性",
                          @"unaware",@"不知道",
                          @"imperative",@"必要",
                          @"terrify",@"恐吓",
                          @"never been more",@"比过去任何时候都要更加",
                          @"pervert",@"败坏",
                          @"motive",@"动机",
                          @"notwithstanding",@"尽管",
                          @"oppsite",@"对面",
                          @"objective",@"客观",
                          @"tactical",@"战术",
                          @"fulfil",@"完成",
                          @"concerted",@"协调",
                          @"conventional",@"传统的",
                          @"somehow",@"以某种方式",
                          @"mutually",@"相互地",
                          @"phenomenon",@"现象",
                          @"apparently",@"显然地",
                          @"presists",@"坚持",
                          @"corrupted",@"损坏",
                          @"elimination",@"消除",
                          @"alliance",@"联盟",
                          @"convertional",@"传统的",
                          @"commitments",@"承诺",
                          @"welsh",@"逃避",
                          @"flexible",@"灵活的",
                          @"presumably",@"大概是",
                          @"obliged",@"感激",
                          @"alternative",@"可供替代的",
                          @"compel",@"强迫",
                          @"democracy",@"民主",
                          @"restatement",@"重述",
                          @"expound",@"阐述了",
                          @"threaten",@"威胁",
                          @"destiny",@"命运",
                          @"vice",@"副的",
                           nil];
        }
        else if([chapter isEqualToString:@"Unite11"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"conscious",@"有意识的",
                          @"lecture",@"演讲",
                          @"conferring",@"授予",
                          @"crave",@"渴望",
                          @"embraced",@"拥抱",
                          @"recollection",@"回忆",
                          @"pursue",@"追求",
                          @"optimism",@"乐观主义",
                          @"prospect",@"展望",
                          @"alter",@"改变",
                          @"prometheus",@"普罗米修斯",
                          @"shifting",@"改变",
                          @"reform",@"改革",
                          @"vibrant",@"充满活力的",
                          @"portion",@"部分",
                          @"rural",@"农村的",
                          @"vital",@"至关重要的",
                          @"inclusive",@"包容的",
                          @"property",@"财产",
                          @"poverty",@"贫困",
                          @"appeal",@"上诉",
                          @"prosperity",@"繁荣",
                          @"sacrificed",@"牺牲",
                          @"profound",@"意义深远的",
                          @"convince",@"说服",
                          @"intensive",@"加强的",
                          @"approach",@"方法",
                          @"vulnerable",@"脆弱的",
                          @"combat",@"战斗",
                          @"promoting",@"促进",
                          @"aspire",@"向往",
                          @"gratitude",@"感激",
                          @"scholars",@"学者，奖学金",
                          @"illustrious",@"著名",
                          @"attachment",@"附件  ",
                          @"regret",@"后悔",
                          @"thus",@"因此",
                          @"subject",@"主题",
                          @"consquently",@"因此",
                          @"inspiration",@"灵感",
                          @"diverse",@"多种多样的",
                          @"respect",@"尊重",
                          @"crucial",@"关键的",
                          @"factors",@"因素",
                          @"intensive",@"加强的",
                          @"liberal",@"自由主义的",
                          @"tolerance",@"容忍",
                          @"welfare",@"福利",
                          @"pullar",@"普拉",
                          @"troops",@"部队",
                          @"delimination",@"分层",
                          @"deposit",@"存款",
                          @"rough",@"粗糙的",
                          @"exploration",@"探索",
                          @"occupy",@"占据",
                          @"context",@"语境",
                          @"privileged",@"有特权的",
                          @"renewed",@"更新",
                          @"delight",@"喜悦的",
                          @"appreciate",@"欣赏",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite10"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"vialbe",@"确切",
                          @"capbilities",@"能力",
                          @"priorty",@"优先",
                          @"domain",@"域",
                          @"mutally",@"互变",
                          @"associate",@"联合",
                          @"overstated",@"夸大",
                          @"annual",@"每年",
                          @"sector",@"部门",
                          @"insurance",@"保险",
                          @"accelerated",@"加速",
                          @"permitting",@"允许",
                          @"marginal",@"边缘的",
                          @"continent",@"大陆",
                          @"trap",@"陷阱",
                          @"agenda",@"议程",
                          @"outcomes",@"结果",
                          @"passivity",@"被动",
                          @"illustrate",@"说明",
                          @"colonial",@"殖民地",
                          @"suffice",@"够了",
                          @"urgent",@"紧急的",
                          @"emerge",@"浮现",
                          @"grace",@"优雅",
                          @"consequences",@"后果",
                          @"legacy",@"遗产",
                          @"negligible",@"可以忽略不计的",
                          @"enterprise",@"企业",
                          @"ultimately",@"最终",
                          @"vicious",@"缺点",
                          @"expectancy",@"期待",
                          @"commodity",@"商品",
                          @"reflect",@"反映",
                          @"domestic",@"国内的",
                          @"positive",@"积极的",
                          @"bypass",@"旁路",
                          @"initiatives",@"主动性",
                          @"reinforce",@"加强",
                          @"debate",@"辩论",
                          @"advocate",@"提倡",
                          @"honorific",@"尊敬的",
                          @"authoritative",@"权威",
                          @"credible",@"可信的",
                          @"influencing",@"影响",
                          @"legislation",@"立法",
                          @"innovation",@"创新",
                          @"atmoshpere",@"大气",
                          @"aware",@"意识到的",
                          @"verture",@"风险",
                          @"equity",@"股权",
                          @"vehicles",@"车辆",
                          @"ehtics",@"伦理",
                          @"supervision",@"监督",
                          @"conclude",@"得出结论",
                          @"modest",@"谦虚的",
                          @"dedicate",@"投入",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite9"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"brace",@"支撑",
                          @"converge",@"收敛",
                          @"summit",@"最高级的",
                          @"deploy",@"部署",
                          @"cannon",@"大炮",
                          @"demonstration",@"示范,游行",
                          @"resident",@"居民",
                          @"disruption",@"破坏",
                          @"cordon",@"警戒线",
                          @"radical",@"基础,激进",
                          @"fierce",@"凶猛的",
                          @"erupt",@"爆发",
                          @"sacred",@"神圣的",
                          @"plateau",@"高原",
                          @"perceive",@"感知",
                          @"implication",@"暗指",
                          @"asylum",@"救济院",
                          @"Discretion",@"判断力",
                          @"messy",@"凌乱的",
                          @"prime",@"主要的,初期",
                          @"discipline",@"学科,纪律,训练",
                          @"residence",@"住宅",
                          @"reflect",@"反照",
                          @"instant",@"瞬间",
                          @"insufficiently",@"不能胜任地",
                          @"substantial",@"本质,大量的",
                          @"merit",@"优点",
                          @"parliamentary",@"议会的",
                          @"tack",@"大头钉",
                          @"thriving",@"繁荣的",
                          @"detest",@"厌恶",
                          @"robust",@"强健的,粗鲁的",
                          @"figure",@"数字,人物,图形",
                          @"territory",@"领土",
                          @"persistent",@"固执的",
                          @"cargo",@"负责",
                          @"Despite",@"轻视,尽管",
                          @"signatory",@"签约的",
                          @"consistently",@"一贯地",
                          @"regulation",@"管理",
                          @"campaign",@"运动,作战",
                          @"ambition",@"野心,追求",
                          @"clamping",@"钳位",
                          @"primarily",@"首先,主要地",
                          @"military",@"军队",
                          @"confront",@"面对",
                          @"fuelled",@"刺激",
                          @"frostiness",@"酷寒",
                          @"atmosphere",@"气氛；大气",
                          @"draw",@"平局",
                          @"literally",@"照字面地,逐字地,正确地",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite8"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"revenue",@"税收，收益",
                          @"paycheck",@"薪水",
                          @"soar",@"高涨",
                          @"figure",@"价格",
                          @"hail",@"冰雹；致敬",
                          @"accompany",@"陪伴，伴随",
                          @"emphasize",@"强调",
                          @"ambitious",@"野心勃勃的；有雄心的",
                          @"flavour",@"香味；滋味",
                          @"swear",@"发誓",
                          @"regulator",@"调整者;审查机关",
                          @"unique",@"独一无二的",
                          @"multinational",@"跨国公司",
                          @"outfit",@"机构；用具",
                          @"concession",@"让步；特许",
                          @"refugee",@"难民",
                          @"diverse",@"不同的；多种多样的；变化多的",
                          @"consultancy",@"咨询公司；顾问工作",
                          @"latch",@"门闩",
                          @"twist",@"扭曲",
                          @"profit",@"有益",
                          @"ascent",@"上升；登高",
                          @"funky",@"时髦的；畏缩的；恶臭的",
                          @"receipt",@"收据；收入",
                          @"periodically",@"定期地；周期性地；偶尔",
                          @"neutral",@"中立的",
                          @"convince",@"说服,使信服",
                          @"February",@"二月",
                          @"May",@"五月",
                          @"Arguably",@"可论证地",
                          @"excess",@"超过,额外的",
                          @"proportion",@"比例；部分；面积",
                          @"frenzy",@"狂暴；狂怒",
                          @"scratch",@"擦伤；抓痕",
                          @"addictive",@"上瘾的",
                          @"criticism",@"批评；考证",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite7"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"jupiter",@"木星",
                          @"November",@"十一月",
                          @"June",@"六月",
                          @"astonish",@"惊讶",
                          @"recipient",@"容器，接受者",
                          @"intensify",@"增强",
                          @"scandal",@"丑闻",
                          @"inbound",@"入境的",
                          @"retail",@"零售",
                          @"leisure",@"空闲",
                          @"surplus",@"剩余；顺差",
                          @"estate",@"财产；身份",
                          @"pageant",@"盛会；游行；",
                          @"previous",@"以前的",
                          @"explosive",@"爆炸的",
                          @"revelations",@"启示录",
                          @"comedic",@"喜剧的",
                          @"congressman",@"国会议员",
                          @"sketch",@"素描",
                          @"potential",@"潜能",
                          @"collusion",@"勾结；共谋",
                          @"controversy",@"争论；论战",
                          @"prominent",@"突出的，显著的",
                          @"insufficient",@"不足的",
                          @"approved",@"被认可的",
                          @"reluctance",@"磁阻；勉强",
                          @"dealmaking",@"交易",
                          @"instinct",@"直觉；天性",
                          @"iteration",@"迭代；反复",
                          @"blockbuster",@"轰动",
                          @"galaxy",@"星系",
                          @"model",@"模型；样式",
                          @"pilot",@"飞行员；试用",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite6"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"engage",@"从事,答应",
                          @"backlash",@"强烈反对",
                          @"regulatory",@"管理的；控制的；调整的",
                          @"console",@"控制台；操纵台",
                          @"stake",@"桩，棍子；赌注；奖金",
                          @"court",@"法院；球场；朝廷",
                          @"diplomat",@"外交家",
                          @"bribery",@"行贿；受贿",
                          @"corruption",@"贪污，腐败；堕落",
                          @"Prosecutor",@"检察官；公诉人",
                          @"bribe",@"贿赂",
                          @"bench",@"长凳；工作台；替补队员",
                          @"endorsement",@"认可，支持；背书",
                          @"territory",@"领土，领域",
                          @"deputy",@"代理人,副的",
                          @"verdict",@"结论；裁定",
                          @"authority",@"权威；权力；当局",
                          @"warehouse",@"仓库",
                          @"surge",@"汹涌；大浪",
                          @"eschew",@"避免；避开；远避",
                          @"dividend",@"红利；股息",
                          @"represent",@"代表；表现",
                          @"narrow",@"海峡；狭窄",
                          @"gap",@"间隙；缺口；差距",
                          @"compensate",@"补偿",
                          @"decline",@"下降；衰退；斜面",
                          @"draw on",@"利用；吸收",
                          @"majority",@"多数；成年",
                          @"speculation",@"投机；推测",
                          @"magnet",@"磁铁",
                          @"evangelist",@"福音传道者",
                          @"dilution",@"稀释，冲淡",
                          @"counterpoint",@"旋律配合；对应物",
                          @"sceptic",@"怀疑论者",
                          @"gloom",@"忧郁；阴暗",
                          @"radical",@"基础；激进分子;数据里的根数",
                          @"endorse",@"背书；认可；签署",
                          @"Precisely",@"精确地；恰恰",
                          @"collaboration",@"合作；勾结",
                          @"racked up",@"积累",
                          @"minivan",@"小型货车",
                          @"maturity",@"成熟；到期；完备",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite5"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"scary",@"胆小的",
                          @"picnic",@"野餐郊游",
                          @"take a shower",@"沐浴",
                          @"boots",@"长统靴",
                          @"gloves",@"手套",
                          @"sandals",@"拖鞋",
                          @"scarf",@"围巾",
                          @"sunnblock",@"防晒霜",
                          @"swimsuit",@"游泳衣",
                          @"towel",@"毛巾",
                          @"round",@"圆形的",
                          @"square",@"正方形",
                          @"blow",@"吹",
                          @"balloon",@"气球",
                          @"hang",@"挂",
                          @"streamer",@"彩带",
                          @"castle",@"城堡",
                          @"clown",@"小丑",
                          @"juggler",@"杂耍",
                          @"magician",@"魔术师",
                          @"present",@"礼物",
                          @"wrap",@"包装",
                          @"apple pie",@"苹果馅饼",
                          @"curry",@"咖喱食品",
                          @"fried",@"炒饭",
                          @"pancake",@"薄煎饼",
                          @"steak",@"牛排",
                          @"bowl",@"碗",
                          @"chopaticks",@"筷子",
                          @"fork",@"餐叉",
                          @"napkin",@"餐巾",
                          @"plate",@"盘子，盆子",
                          @"spoon",@"匙，调羹",
                          @"juicy",@"多汁的",
                          @"salty",@"咸的",
                          @"sour",@"有酸味的",
                          @"spicy",@"辛辣的",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite4"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"soap",@"肥皂",
                          @"docker",@"码头工人",
                          @"Hibernate",@"过冬",
                          @"snippet",@"片断",
                          @"Cushion",@"垫子",
                          @"fork",@"分叉",
                          @"simulate",@"模仿的",
                          @"drop-in",@"不速之客，顺便",
                          @"patchy",@"有补丁的",
                          @"throttle",@"节流阀",
                          @"implicit",@"暗示的",
                          @"schema",@"模式；计划",
                          @"omit",@"省略；遗漏",
                          @"rule",@"统治；规则",
                          @"October",@"十月",
                          @"decimal",@"小数的；十进位的",
                          @"Hyper",@"宣传人员；亢奋的",
                          @"Introspector",@"内省",
                          @"idempotent",@"幂等",
                          @"aggregation",@"聚合，聚集",
                          @"column",@"纵队，圆柱",
                          @"Normalize",@"使正常化，使标准化",
                          @"projection",@"投射；规划",
                          @"Lambda",@"希腊字母的第11个",
                          @"Racket",@"球拍；吵闹",
                          @"tuning",@"调谐；调音",
                          @"unification",@"统一；一致",
                          @"infrastructure",@"基础设施",
                          @"Notation",@"符号；乐谱；注释",
                          @"Thrift",@"节俭；节约",
                          @"bean",@"豆；毫无价值的东西",
                          @"portable",@"手提的，轻便的",
                          @"Reflection",@"反射；沉思",
                          @"Field",@"领域；牧场",
                          @"Retention",@"保留；扣留",
                          @"generic",@"类的；一般的",
                          @"meta",@"元语言",
                          @"lesbian",@"女同性恋者",
                          @"hygiene",@"卫生",
                          @"Pseudo",@"伪君子，假的",
                          @"Verter",@"草木，绿色的",
                          @"Liberal",@"自由主义",
                          @"breadcrumb",@"面包屑",
                          @"role",@"角色；任务",
                          nil];
        }
        else if([chapter isEqualToString:@"Unite3"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"sail ",@"航行；启航",
                          @"Envelope ",@" 信封，封皮",
                          @"Term ",@"术语；学期；条款",
                          @"glossary ",@"术语;表；词汇表",
                          @"Consortium ",@"财团；联合",
                          @"solicit ",@"征求；招揽；请求",
                          @"brace",@" 支柱；大括号",
                          @"fantasy ",@"幻想；白日梦；幻觉",
                          @"integration ",@"集成；综合",
                          @"religious",@" 宗教的；虔诚的；严谨的",
                          @"wary",@" 谨慎的；机警的",
                          @"identity  ",@"身份；一致；特性；恒等式",
                          @"exploit",@"勋绩；功绩; 开发",
                          @"unrolling",@"展开，铺开；显示",
                          @"substitute ",@"代用品；代替者",
                          @"sentinel",@" 哨兵. 守卫",
                          @"algorithm ",@"算法，运算法则",
                          @"precise ",@"精确的；明确的；严格的",
                          @"tuning ",@"调谐；调音",
                          @"philosophy ",@"哲学；哲理；人生观",
                          @"refactor",@" 重构",
                          @"psychological ",@"心理的；心理学的；精神上的",
                          @"opportunity ",@"时机，机会",
                          @"variation ",@"变化；变异",
                          @"scaffolding ",@"脚手架",
                          @"individual ",@"个人，个体；独特的",
                          @"proportion",@" 比例；部分；面积；均衡",
                          @"classification ",@"分类；类别，等级",
                          @"compound",@"化合物；混合",
                          @"trick ",@"诡计；恶作剧；窍门；",
                          @"recommend ",@"推荐，介绍；劝告",
                          @"apply",@"申请；适用；请求",
                          @"relevant ",@"相关的；中肯的；有重大关系的；有意义的",
                          @"defect",@" 缺点，缺陷. 变节；叛变",
                          @"evaluate ",@"评价；估价",
                          @"parenthesis ",@",插入语, 圆括号",
                          @"clarify ",@"澄清；阐明",
                          @"positively ",@"肯定地；明确地；断然地",
                          @"stair ",@"楼梯，阶梯",
                          @"perspective ",@"观点；远景；透视",
                          @"specific",@" 特性；细节；明确的；详细的",
                          nil];
            
        }
            else if([chapter isEqualToString:@"Unite2"]){
                originArray =[NSMutableArray arrayWithObjects:
                              @"organizing ",@"组织；使有机化",
                              @"statements",@" 声明；报告",
                              @"resort ",@"凭借，手段；求助",
                              @"absence ",@"没有；缺乏；缺席；不注意",
                              @"abbreviation",@" 缩写；缩写词",
                              @"scope",@" 范围；余地；视野",
                              @"reference ",@"参考，参照；涉及，提及；介绍信；证明书",
                              @"literacy",@" 读写能力；精通文学",
                              @"stub ",@"存根；烟蒂；树桩；断株",
                              @"aid ",@"援助；帮助；助手",
                              @"robustness ",@" 稳健性；健壮性",
                              @"elevation ",@" 高地；海拔；提高",
                              @"shallow",@" 浅滩. 浅的；肤浅的",
                              @"inheritance",@" 继承；遗传；遗产",
                              @"issue ",@"问题；流出；发行物. 发行，发布",
                              @"semantic ",@"语义的",
                              @"oriented",@" 调整；使朝向；确定…的方位. 导向的",
                              @"theory",@" 理论；原理；学说；推测",
                              @"collaborative ",@"合作的，协作的",
                              @"conquer ",@"战胜，征服；攻克;胜利",
                              @"consciously ",@"自觉地；有意识地",
                              @"contract",@" 合同；婚约",
                              @"formalize ",@"使形式化；使正式；拘泥礼仪",
                              @"cohesion ",@"凝聚；结合；内聚力",
                              @"hierarchies",@" 阶层，层级，分类",
                              @"heuristic",@" 启发式的；探索的",
                              @"criterion ",@"标准；准则；规范",
                              @"anticipate ",@"预期，期望；占先",
                              @"barrier",@" 障碍物，屏障",
                              @"privacy",@" 隐私；秘密；隐居",
                              @"encapsulate ",@"压缩；将…装入胶囊；概述",
                              @"balance ",@"平衡；余额；匀称；抵销",
                              @"routine ",@"小程序；日常工作；例行公事",
                              @"stratification ",@"层理；成层",
                              @"leanness ",@" 瘦；贫瘠；缺乏",
                              @"coupling",@" 耦合；结合，联结",
                              @"loose ",@"放纵；放任；发射. 宽松的",
                              @"promotion ",@"提升，晋升；推销，促销",
                              @"batch",@"一批；一炉；. 分批处理",
                              @"essential ",@"本质；要素；要点；必需品",
                              @"concept",@" 观念，概念",
                              nil];
            }
                else if([chapter isEqualToString:@"Unite1"]){
                    originArray =[NSMutableArray arrayWithObjects:
                                  @"emergent",@" 紧急的；浮现的；自然发生的",
                                  @"involve ",@"包含；牵涉；使陷于",
                                  @"tradeoff ",@"权衡；折衷；（公平）交易",
                                  @"tidy ",@"整齐的；相当大的",
                                  @"wave",@" 波动；波浪；高潮；挥手示意",
                                  @"convention ",@"惯例；[计] 约定；[法] 协定；习俗",
                                  @"upstream",@"上游部门",
                                  @"specify ",@"指定；详细说明；列举",
                                  @"feasibility ",@"可行性；可能性",
                                  @"tolerance",@" 公差；宽容；容忍",
                                  @"typical",@" 典型的；特有的；象征性的",
                                  @"evolution",@" 演变；进化论；进展",
                                  @"myth",@" 神话；虚构的人",
                                  @"approach ",@" 方法；途径；接近",
                                  @"utterly",@" 完全地；绝对地",
                                  @"prerequisite",@" 先决条件. 首要必备的",
                                  @"measure",@" 测量；措施；程度；尺寸",
                                  @"sloppy",@" 草率的；粗心的",
                                  @"paradigm ",@"范例；词形变化表",
                                  @"intellectual ",@"智力的；聪明的；理智的",
                                  @"tearing",@" 撕裂的；痛苦的；裂开",
                                  @"inspection",@" 视察，检查",
                                  @"architect",@" 建筑师 缔造者",
                                  @"agile",@" 敏捷的；机敏的；活泼的",
                                  @"dummy",@" 傀儡；哑巴；仿制品；假的",
                                  @"accretion ",@"添加；增加物",
                                  @"trial ",@"试验；审讯；努力；磨炼. 试验的",
                                  @"conceptualizing ",@"概念化",
                                  @"deterministic",@" 确定性的；命运注定论的",
                                  @"ether",@"乙醚 以太；苍天",
                                  @"analogy",@" 类比；类推；类似",
                                  @"metaphor ",@"暗喻，隐喻；比喻说法",
                                  @"hub ",@"中心",
                                  @"stomach",@"胃；腹部. 忍受",
                                  @"independent ",@"独立的；单独的；无党派的",
                                  @"endorses",@" 背书；认可；签署；赞同；在背面签名",
                                  @"pattern ",@" 模式；图案；样品",
                                  @"yogurt ",@" 酸奶酪",
                                  nil];
        }
    }
    else if([userType isEqualToString:@"root"]){
        if([chapter isEqualToString:@"Unite1"]){
            originArray =[NSMutableArray arrayWithObjects:
                          @"acid",@"sour，sharp，酸的，尖锐的",
                          @"acu",@"sharp，尖锐的",
                          @"act,ag",@"do,drive,做，行动，推动",
                          @"agogue",@"leader领导",
                          @"agon",@"contest 争夺，竞争",
                          @"agr",@"field 土地，田野",
                          @"all,ol",@"grow,feed,生长，喂养，滋养",
                          @"alb",@"white,白色",
                          @"alg",@"pain 痛",
                          @"alt",@"high, 高",
                          @"ak,alter",@"oter,其他的，另外的",
                          @"am",@"爱",
                          @"ang,anx",@"torment,strangle,折磨，扼死",
                          @"angl,angul",@"corner,角",
                          @"anim",@"life,anger,生命,愤怒",
                          @"ann,enn",@"year,年",
                          @"anthrop",@"man,human，人，人类",
                          @"apt,ept",@"fit,ability,适应，能力",
                          @"aqua,aque,aqui",@"water,水",
                          @"arch",@"chief,ruler,首领,统治者",
                          @"arithm",@"count,计算",
                          @"arm",@"weapon,武器",
                          @"art",@"joint,关节，结合点",
                          @"art",@"skill,艺术，技巧",
                          @"asper",@"rough，粗鲁，粗暴",
                          @"aster,astr",@"star,星",
                          @"athl",@"contest,竞赛，争夺",
                          @"audi",@"hear，听",
                          @"aug,auth",@"increase,增加",
                          @"avi",@"bird,鸟",
                          @"aw",@"fright,惊骇,约束",
                          @"band",@"bind,捆绑，约束",
                          @"bar",@"bar,杆，棒，阻碍",
                          @"bas,bat",@"go,走",
                          @"bat",@"beat,打,捶打",
                          @"bel",@"war,战争",
                          @"bio",@"life,生命,生物",
                          @"brew",@"short,短的,简略的",
                          nil];
        }
    }


    NSMutableArray* array = [[NSMutableArray alloc] init];

    for(int index = 0;index < originArray.count;index=index+2){
        AEnglistItem* item = [AEnglistItem new];
        item.english = [originArray objectAtIndex:index];
        item.chinese = [originArray objectAtIndex:index+1];
        [array addObject:item];
    }

    return array;
}

@end
